# Generated by Django 3.1.3 on 2020-11-14 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loja_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nome', models.CharField(choices=[('Sistema Solar', 'Sistema Solar'), ('Exoplanetas', 'Exoplanetas')], max_length=13, verbose_name='Categoria')),
                ('cat_slug', models.SlugField(max_length=100)),
                ('cat_criacao', models.DateTimeField(auto_now_add=True)),
                ('cat_modificacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loja - Categoria',
                'verbose_name_plural': 'Loja - Categorias',
                'ordering': ['cat_nome'],
            },
        ),
        migrations.CreateModel(
            name='loja_produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nome', models.CharField(max_length=13, verbose_name='Planeta / Produto')),
                ('prod_slug', models.SlugField(max_length=100)),
                ('prod_criacao', models.DateTimeField(auto_now_add=True)),
                ('prod_modificacao', models.DateTimeField(auto_now=True)),
                ('prod_descricao', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('prod_valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('prod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio_loja.loja_categoria')),
            ],
            options={
                'verbose_name': 'Loja - Produto',
                'verbose_name_plural': 'Loja - Produtos',
                'ordering': ['prod_nome'],
            },
        ),
    ]
