# Generated by Django 3.1.3 on 2020-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja_categoria',
            name='cat_nome',
            field=models.CharField(max_length=13, verbose_name='Categoria'),
        ),
    ]
