# Generated by Django 3.1.3 on 2020-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planeta', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Indeterminado', 'Indeterminado'), ('Rochoso', 'Rochoso'), ('Gasoso', 'Gasoso')], max_length=13)),
                ('massa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_mod', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
